# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170724_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.Post'),
        ),
    ]
